sudo: true
before_install:
  - "export DISPLAY=:99.0"
  - "sudo apt-get install xclip --no-install-recommends --yes"
  - "sh -e /etc/init.d/xvfb start"
language: perl6
perl6:
  - latest
install:
    - rakudobrew build-panda
    - panda installdeps .
